--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: dlk_torrecontrol; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dlk_torrecontrol;


ALTER SCHEMA dlk_torrecontrol OWNER TO postgres;

--
-- Name: dwh_torrecontrol; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dwh_torrecontrol;


ALTER SCHEMA dwh_torrecontrol OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Dlk_cat_acc_claim_empleados; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_claim_empleados" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_claim_empleados" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_claim_empleados_Id_seq; Type: SEQUENCE; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_claim_empleados" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dlk_torrecontrol."Dlk_cat_acc_claim_empleados_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Dlk_cat_acc_claim_roles; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_claim_roles" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_claim_roles" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_claim_roles_Id_seq; Type: SEQUENCE; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_claim_roles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dlk_torrecontrol."Dlk_cat_acc_claim_roles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Dlk_cat_acc_empleados; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_empleados" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_empleados" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_empleados_roles; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_empleados_roles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_empleados_roles" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_login_empleados; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_login_empleados" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_login_empleados" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_roles; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_roles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_roles" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_token_empleados; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_token_empleados" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_token_empleados" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_devolucion_pedido; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido" (
    "Cod_estado_devolucion" text NOT NULL,
    "Md_uuid" text NOT NULL,
    "Md_date" timestamp without time zone NOT NULL,
    "Id" integer NOT NULL,
    "Des_estado_devolucion" text
);


ALTER TABLE dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_devolucion_pedido_Id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE SEQUENCE dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido_Id_seq" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_devolucion_pedido_Id_seq; Type: SEQUENCE OWNED BY; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER SEQUENCE dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido_Id_seq" OWNED BY dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido"."Id";


--
-- Name: Tdc_cat_estados_envio_pedido; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol."Tdc_cat_estados_envio_pedido" (
    "Cod_estado_envio" text NOT NULL,
    "Md_uuid" text NOT NULL,
    "Md_date" timestamp without time zone NOT NULL,
    "Id" integer NOT NULL,
    "Des_estado_envio" text
);


ALTER TABLE dwh_torrecontrol."Tdc_cat_estados_envio_pedido" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_envio_pedido_Id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE SEQUENCE dwh_torrecontrol."Tdc_cat_estados_envio_pedido_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dwh_torrecontrol."Tdc_cat_estados_envio_pedido_Id_seq" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_envio_pedido_Id_seq; Type: SEQUENCE OWNED BY; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER SEQUENCE dwh_torrecontrol."Tdc_cat_estados_envio_pedido_Id_seq" OWNED BY dwh_torrecontrol."Tdc_cat_estados_envio_pedido"."Id";


--
-- Name: Tdc_cat_estados_pago_pedido; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol."Tdc_cat_estados_pago_pedido" (
    "Cod_estado_pago" text NOT NULL,
    "Md_uuid" text NOT NULL,
    "Md_date" timestamp without time zone NOT NULL,
    "Id" integer NOT NULL,
    "Des_estado_pago" text
);


ALTER TABLE dwh_torrecontrol."Tdc_cat_estados_pago_pedido" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_pago_pedido_Id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE SEQUENCE dwh_torrecontrol."Tdc_cat_estados_pago_pedido_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dwh_torrecontrol."Tdc_cat_estados_pago_pedido_Id_seq" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_pago_pedido_Id_seq; Type: SEQUENCE OWNED BY; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER SEQUENCE dwh_torrecontrol."Tdc_cat_estados_pago_pedido_Id_seq" OWNED BY dwh_torrecontrol."Tdc_cat_estados_pago_pedido"."Id";


--
-- Name: Tdc_cat_lineas_distribucion; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol."Tdc_cat_lineas_distribucion" (
    "Cod_linea" text NOT NULL,
    "Md_uuid" text NOT NULL,
    "Md_date" timestamp without time zone NOT NULL,
    "Id" integer NOT NULL,
    "Cod_provincia" text NOT NULL,
    "Cod_municipio" text NOT NULL,
    "Cod_barrio" text NOT NULL
);


ALTER TABLE dwh_torrecontrol."Tdc_cat_lineas_distribucion" OWNER TO postgres;

--
-- Name: Tdc_cat_lineas_distribucion_Id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE SEQUENCE dwh_torrecontrol."Tdc_cat_lineas_distribucion_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dwh_torrecontrol."Tdc_cat_lineas_distribucion_Id_seq" OWNER TO postgres;

--
-- Name: Tdc_cat_lineas_distribucion_Id_seq; Type: SEQUENCE OWNED BY; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER SEQUENCE dwh_torrecontrol."Tdc_cat_lineas_distribucion_Id_seq" OWNED BY dwh_torrecontrol."Tdc_cat_lineas_distribucion"."Id";


--
-- Name: Tdc_tch_estado_pedidos; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol."Tdc_tch_estado_pedidos" (
    "Id" integer NOT NULL,
    "Md_uuid" text NOT NULL,
    "Md_date" timestamp without time zone NOT NULL,
    "Cod_pedido" text NOT NULL,
    "Cod_estado_envio" text,
    "Cod_estado_pago" text,
    "Cod_estado_devolucion" text,
    "Cod_linea" text NOT NULL
);


ALTER TABLE dwh_torrecontrol."Tdc_tch_estado_pedidos" OWNER TO postgres;

--
-- Name: Tdc_tch_estado_pedidos_Id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE SEQUENCE dwh_torrecontrol."Tdc_tch_estado_pedidos_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dwh_torrecontrol."Tdc_tch_estado_pedidos_Id_seq" OWNER TO postgres;

--
-- Name: Tdc_tch_estado_pedidos_Id_seq; Type: SEQUENCE OWNED BY; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER SEQUENCE dwh_torrecontrol."Tdc_tch_estado_pedidos_Id_seq" OWNED BY dwh_torrecontrol."Tdc_tch_estado_pedidos"."Id";


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: Tdc_cat_estados_devolucion_pedido Id; Type: DEFAULT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido" ALTER COLUMN "Id" SET DEFAULT nextval('dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido_Id_seq"'::regclass);


--
-- Name: Tdc_cat_estados_envio_pedido Id; Type: DEFAULT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_estados_envio_pedido" ALTER COLUMN "Id" SET DEFAULT nextval('dwh_torrecontrol."Tdc_cat_estados_envio_pedido_Id_seq"'::regclass);


--
-- Name: Tdc_cat_estados_pago_pedido Id; Type: DEFAULT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_estados_pago_pedido" ALTER COLUMN "Id" SET DEFAULT nextval('dwh_torrecontrol."Tdc_cat_estados_pago_pedido_Id_seq"'::regclass);


--
-- Name: Tdc_cat_lineas_distribucion Id; Type: DEFAULT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_lineas_distribucion" ALTER COLUMN "Id" SET DEFAULT nextval('dwh_torrecontrol."Tdc_cat_lineas_distribucion_Id_seq"'::regclass);


--
-- Name: Tdc_tch_estado_pedidos Id; Type: DEFAULT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_tch_estado_pedidos" ALTER COLUMN "Id" SET DEFAULT nextval('dwh_torrecontrol."Tdc_tch_estado_pedidos_Id_seq"'::regclass);


--
-- Data for Name: Dlk_cat_acc_claim_empleados; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--



--
-- Data for Name: Dlk_cat_acc_claim_roles; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--



--
-- Data for Name: Dlk_cat_acc_empleados; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

INSERT INTO dlk_torrecontrol."Dlk_cat_acc_empleados" VALUES ('53cfeca9-bb2c-4254-a2d1-616dded509e2', 'sergio@gmail.com', 'SERGIO@GMAIL.COM', 'sergio@gmail.com', 'SERGIO@GMAIL.COM', false, 'AQAAAAEAACcQAAAAEIFgJolByE1HBIbdozJoiOqZINF6DcGFYvcyyZvXRLF+n7O5W9XOgHigRrbzGLQ/BQ==', 'T5KPLO5NDMKMK4NXQECZB2SI3G2AQ7JZ', '34c50489-114f-4092-9f2b-f07bb923d225', NULL, false, false, NULL, true, 0);
INSERT INTO dlk_torrecontrol."Dlk_cat_acc_empleados" VALUES ('1dc20d88-0e94-465e-9905-b624f32825b7', 'moises@gmail.com', 'MOISES@GMAIL.COM', 'moises@gmail.com', 'MOISES@GMAIL.COM', false, 'AQAAAAEAACcQAAAAEDNXaXHlQLGV+UqJPz665ixY/cvf6Ma78WqNff6s0/YOkWTuUGfRpCTrZHCmYYY5dg==', 'XDBMYVYVJGQ3NTICGNGH2S77QFZFLC6V', '9fd31b15-dd58-4f8c-9c7c-99ec3b1cc573', NULL, false, false, NULL, true, 0);
INSERT INTO dlk_torrecontrol."Dlk_cat_acc_empleados" VALUES ('55f7607d-da9d-40ea-9889-5b8aa5b63d03', 'javier@gmail.com', 'JAVIER@GMAIL.COM', 'javier@gmail.com', 'JAVIER@GMAIL.COM', false, 'AQAAAAEAACcQAAAAECDv5QfAR9T04suVDlEG1hnXMNzwWfefGpYokspc16bzl/3KC9uJw/38W3TZCV7a4g==', '4IIYOC6BXT74HFUYX7AS2REJRI5BX42R', '2f5094d6-4b1f-401c-b751-a0623428cb57', NULL, false, false, NULL, true, 0);
INSERT INTO dlk_torrecontrol."Dlk_cat_acc_empleados" VALUES ('e7d163fe-69a3-46c1-b7f3-7c5d73b3f7ba', 'sergiodiazcampos@gmail.com', 'SERGIODIAZCAMPOS@GMAIL.COM', 'sergiodiazcampos@gmail.com', 'SERGIODIAZCAMPOS@GMAIL.COM', false, NULL, 'EB6PYJTZCDAJS3SBL4G7FNLIYYLM2NFL', 'ee63ff12-a614-4b6a-b6a7-78dbbb1a2f61', NULL, false, false, NULL, true, 0);


--
-- Data for Name: Dlk_cat_acc_empleados_roles; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

INSERT INTO dlk_torrecontrol."Dlk_cat_acc_empleados_roles" VALUES ('53cfeca9-bb2c-4254-a2d1-616dded509e2', '0');
INSERT INTO dlk_torrecontrol."Dlk_cat_acc_empleados_roles" VALUES ('1dc20d88-0e94-465e-9905-b624f32825b7', '1');
INSERT INTO dlk_torrecontrol."Dlk_cat_acc_empleados_roles" VALUES ('55f7607d-da9d-40ea-9889-5b8aa5b63d03', '2');


--
-- Data for Name: Dlk_cat_acc_login_empleados; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

INSERT INTO dlk_torrecontrol."Dlk_cat_acc_login_empleados" VALUES ('Google', '100155944581264970326', 'Google', 'e7d163fe-69a3-46c1-b7f3-7c5d73b3f7ba');


--
-- Data for Name: Dlk_cat_acc_roles; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

INSERT INTO dlk_torrecontrol."Dlk_cat_acc_roles" VALUES ('0', 'Administrators', 'Admin', 'null');
INSERT INTO dlk_torrecontrol."Dlk_cat_acc_roles" VALUES ('1', 'Employees', 'Employee', 'null');
INSERT INTO dlk_torrecontrol."Dlk_cat_acc_roles" VALUES ('2', 'Users', 'User', 'null');


--
-- Data for Name: Dlk_cat_acc_token_empleados; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--



--
-- Data for Name: Tdc_cat_estados_devolucion_pedido; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

INSERT INTO dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido" VALUES ('A', '1', '2022-11-07 10:24:00', 1, 'Aceptada');
INSERT INTO dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido" VALUES ('R', '2', '2022-11-07 10:24:00', 2, 'Rechazada');


--
-- Data for Name: Tdc_cat_estados_envio_pedido; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

INSERT INTO dwh_torrecontrol."Tdc_cat_estados_envio_pedido" VALUES ('S1', '1', '2022-11-07 10:23:00', 1, 'Solicitado');
INSERT INTO dwh_torrecontrol."Tdc_cat_estados_envio_pedido" VALUES ('R1', '2', '2022-11-07 10:23:00', 2, 'Registrado en almacén');


--
-- Data for Name: Tdc_cat_estados_pago_pedido; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

INSERT INTO dwh_torrecontrol."Tdc_cat_estados_pago_pedido" VALUES ('E1', '1', '2022-11-07 10:24:00', 1, 'Emitida factura');
INSERT INTO dwh_torrecontrol."Tdc_cat_estados_pago_pedido" VALUES ('R', '2', '2022-11-07 10:24:00', 2, 'Rechazado');


--
-- Data for Name: Tdc_cat_lineas_distribucion; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

INSERT INTO dwh_torrecontrol."Tdc_cat_lineas_distribucion" VALUES ('SEV-SEV-NER', '1', '2022-11-07 10:10:00', 2, 'SEV', 'SEV', 'NER');
INSERT INTO dwh_torrecontrol."Tdc_cat_lineas_distribucion" VALUES ('SEV-SEV-AMA', '2', '2022-11-07 10:11:00', 3, 'SEV', 'SEV', 'AMA');


--
-- Data for Name: Tdc_tch_estado_pedidos; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

INSERT INTO dwh_torrecontrol."Tdc_tch_estado_pedidos" VALUES (1, '1', '2022-11-07 10:25:00', '1', 'S1', 'E1', 'A', 'SEV-SEV-NER');
INSERT INTO dwh_torrecontrol."Tdc_tch_estado_pedidos" VALUES (2, '2', '2022-11-07 10:25:00', '2', 'R1', 'R', 'R', 'SEV-SEV-AMA');


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20221112165038_prueba-identity-login-register', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221113102825_prueba-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221113103005_prueba-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221113103330_prueba-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221113103437_prueba-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221113215918_migracion-dlk-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221129122512_dlk-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221129122959_dlk-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221129124229_dlk-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221116163026_SeedRoles', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20221129160420_dlk-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20230104173633_dlk-migracion-1', '6.0.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20230104175502_dlk-migracion-1', '6.0.10');


--
-- Name: Dlk_cat_acc_claim_empleados_Id_seq; Type: SEQUENCE SET; Schema: dlk_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dlk_torrecontrol."Dlk_cat_acc_claim_empleados_Id_seq"', 1, false);


--
-- Name: Dlk_cat_acc_claim_roles_Id_seq; Type: SEQUENCE SET; Schema: dlk_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dlk_torrecontrol."Dlk_cat_acc_claim_roles_Id_seq"', 1, false);


--
-- Name: Tdc_cat_estados_devolucion_pedido_Id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido_Id_seq"', 2, true);


--
-- Name: Tdc_cat_estados_envio_pedido_Id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol."Tdc_cat_estados_envio_pedido_Id_seq"', 2, true);


--
-- Name: Tdc_cat_estados_pago_pedido_Id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol."Tdc_cat_estados_pago_pedido_Id_seq"', 2, true);


--
-- Name: Tdc_cat_lineas_distribucion_Id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol."Tdc_cat_lineas_distribucion_Id_seq"', 3, true);


--
-- Name: Tdc_tch_estado_pedidos_Id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol."Tdc_tch_estado_pedidos_Id_seq"', 2, true);


--
-- Name: Dlk_cat_acc_claim_empleados PK_Dlk_cat_acc_claim_empleados; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_claim_empleados"
    ADD CONSTRAINT "PK_Dlk_cat_acc_claim_empleados" PRIMARY KEY ("Id");


--
-- Name: Dlk_cat_acc_claim_roles PK_Dlk_cat_acc_claim_roles; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_claim_roles"
    ADD CONSTRAINT "PK_Dlk_cat_acc_claim_roles" PRIMARY KEY ("Id");


--
-- Name: Dlk_cat_acc_empleados PK_Dlk_cat_acc_empleados; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_empleados"
    ADD CONSTRAINT "PK_Dlk_cat_acc_empleados" PRIMARY KEY ("Id");


--
-- Name: Dlk_cat_acc_empleados_roles PK_Dlk_cat_acc_empleados_roles; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_empleados_roles"
    ADD CONSTRAINT "PK_Dlk_cat_acc_empleados_roles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: Dlk_cat_acc_login_empleados PK_Dlk_cat_acc_login_empleados; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_login_empleados"
    ADD CONSTRAINT "PK_Dlk_cat_acc_login_empleados" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: Dlk_cat_acc_roles PK_Dlk_cat_acc_roles; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_roles"
    ADD CONSTRAINT "PK_Dlk_cat_acc_roles" PRIMARY KEY ("Id");


--
-- Name: Dlk_cat_acc_token_empleados PK_Dlk_cat_acc_token_empleados; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_token_empleados"
    ADD CONSTRAINT "PK_Dlk_cat_acc_token_empleados" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: Tdc_cat_estados_devolucion_pedido PK_Tdc_cat_estados_devolucion_pedido; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido"
    ADD CONSTRAINT "PK_Tdc_cat_estados_devolucion_pedido" PRIMARY KEY ("Cod_estado_devolucion");


--
-- Name: Tdc_cat_estados_envio_pedido PK_Tdc_cat_estados_envio_pedido; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_estados_envio_pedido"
    ADD CONSTRAINT "PK_Tdc_cat_estados_envio_pedido" PRIMARY KEY ("Cod_estado_envio");


--
-- Name: Tdc_cat_estados_pago_pedido PK_Tdc_cat_estados_pago_pedido; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_estados_pago_pedido"
    ADD CONSTRAINT "PK_Tdc_cat_estados_pago_pedido" PRIMARY KEY ("Cod_estado_pago");


--
-- Name: Tdc_cat_lineas_distribucion PK_Tdc_cat_lineas_distribucion; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_cat_lineas_distribucion"
    ADD CONSTRAINT "PK_Tdc_cat_lineas_distribucion" PRIMARY KEY ("Cod_linea");


--
-- Name: Tdc_tch_estado_pedidos PK_Tdc_tch_estado_pedidos; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_tch_estado_pedidos"
    ADD CONSTRAINT "PK_Tdc_tch_estado_pedidos" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "EmailIndex" ON dlk_torrecontrol."Dlk_cat_acc_empleados" USING btree ("NormalizedEmail");


--
-- Name: IX_Dlk_cat_acc_claim_empleados_UserId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Dlk_cat_acc_claim_empleados_UserId" ON dlk_torrecontrol."Dlk_cat_acc_claim_empleados" USING btree ("UserId");


--
-- Name: IX_Dlk_cat_acc_claim_roles_RoleId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Dlk_cat_acc_claim_roles_RoleId" ON dlk_torrecontrol."Dlk_cat_acc_claim_roles" USING btree ("RoleId");


--
-- Name: IX_Dlk_cat_acc_empleados_roles_RoleId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Dlk_cat_acc_empleados_roles_RoleId" ON dlk_torrecontrol."Dlk_cat_acc_empleados_roles" USING btree ("RoleId");


--
-- Name: IX_Dlk_cat_acc_login_empleados_UserId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Dlk_cat_acc_login_empleados_UserId" ON dlk_torrecontrol."Dlk_cat_acc_login_empleados" USING btree ("UserId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON dlk_torrecontrol."Dlk_cat_acc_roles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON dlk_torrecontrol."Dlk_cat_acc_empleados" USING btree ("NormalizedUserName");


--
-- Name: IX_Tdc_tch_estado_pedidos_Cod_estado_devolucion; Type: INDEX; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Tdc_tch_estado_pedidos_Cod_estado_devolucion" ON dwh_torrecontrol."Tdc_tch_estado_pedidos" USING btree ("Cod_estado_devolucion");


--
-- Name: IX_Tdc_tch_estado_pedidos_Cod_estado_envio; Type: INDEX; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Tdc_tch_estado_pedidos_Cod_estado_envio" ON dwh_torrecontrol."Tdc_tch_estado_pedidos" USING btree ("Cod_estado_envio");


--
-- Name: IX_Tdc_tch_estado_pedidos_Cod_estado_pago; Type: INDEX; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Tdc_tch_estado_pedidos_Cod_estado_pago" ON dwh_torrecontrol."Tdc_tch_estado_pedidos" USING btree ("Cod_estado_pago");


--
-- Name: IX_Tdc_tch_estado_pedidos_Cod_linea; Type: INDEX; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Tdc_tch_estado_pedidos_Cod_linea" ON dwh_torrecontrol."Tdc_tch_estado_pedidos" USING btree ("Cod_linea");


--
-- Name: Dlk_cat_acc_claim_empleados FK_Dlk_cat_acc_claim_empleados_Dlk_cat_acc_empleados_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_claim_empleados"
    ADD CONSTRAINT "FK_Dlk_cat_acc_claim_empleados_Dlk_cat_acc_empleados_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."Dlk_cat_acc_empleados"("Id") ON DELETE CASCADE;


--
-- Name: Dlk_cat_acc_claim_roles FK_Dlk_cat_acc_claim_roles_Dlk_cat_acc_roles_RoleId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_claim_roles"
    ADD CONSTRAINT "FK_Dlk_cat_acc_claim_roles_Dlk_cat_acc_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES dlk_torrecontrol."Dlk_cat_acc_roles"("Id") ON DELETE CASCADE;


--
-- Name: Dlk_cat_acc_empleados_roles FK_Dlk_cat_acc_empleados_roles_Dlk_cat_acc_empleados_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_empleados_roles"
    ADD CONSTRAINT "FK_Dlk_cat_acc_empleados_roles_Dlk_cat_acc_empleados_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."Dlk_cat_acc_empleados"("Id") ON DELETE CASCADE;


--
-- Name: Dlk_cat_acc_empleados_roles FK_Dlk_cat_acc_empleados_roles_Dlk_cat_acc_roles_RoleId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_empleados_roles"
    ADD CONSTRAINT "FK_Dlk_cat_acc_empleados_roles_Dlk_cat_acc_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES dlk_torrecontrol."Dlk_cat_acc_roles"("Id") ON DELETE CASCADE;


--
-- Name: Dlk_cat_acc_login_empleados FK_Dlk_cat_acc_login_empleados_Dlk_cat_acc_empleados_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_login_empleados"
    ADD CONSTRAINT "FK_Dlk_cat_acc_login_empleados_Dlk_cat_acc_empleados_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."Dlk_cat_acc_empleados"("Id") ON DELETE CASCADE;


--
-- Name: Dlk_cat_acc_token_empleados FK_Dlk_cat_acc_token_empleados_Dlk_cat_acc_empleados_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_token_empleados"
    ADD CONSTRAINT "FK_Dlk_cat_acc_token_empleados_Dlk_cat_acc_empleados_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."Dlk_cat_acc_empleados"("Id") ON DELETE CASCADE;


--
-- Name: Tdc_tch_estado_pedidos FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_devolucion_pedido_Co~; Type: FK CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_tch_estado_pedidos"
    ADD CONSTRAINT "FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_devolucion_pedido_Co~" FOREIGN KEY ("Cod_estado_devolucion") REFERENCES dwh_torrecontrol."Tdc_cat_estados_devolucion_pedido"("Cod_estado_devolucion");


--
-- Name: Tdc_tch_estado_pedidos FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_envio_pedido_Cod_est~; Type: FK CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_tch_estado_pedidos"
    ADD CONSTRAINT "FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_envio_pedido_Cod_est~" FOREIGN KEY ("Cod_estado_envio") REFERENCES dwh_torrecontrol."Tdc_cat_estados_envio_pedido"("Cod_estado_envio");


--
-- Name: Tdc_tch_estado_pedidos FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_pago_pedido_Cod_esta~; Type: FK CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_tch_estado_pedidos"
    ADD CONSTRAINT "FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_pago_pedido_Cod_esta~" FOREIGN KEY ("Cod_estado_pago") REFERENCES dwh_torrecontrol."Tdc_cat_estados_pago_pedido"("Cod_estado_pago");


--
-- Name: Tdc_tch_estado_pedidos FK_Tdc_tch_estado_pedidos_Tdc_cat_lineas_distribucion_Cod_linea; Type: FK CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol."Tdc_tch_estado_pedidos"
    ADD CONSTRAINT "FK_Tdc_tch_estado_pedidos_Tdc_cat_lineas_distribucion_Cod_linea" FOREIGN KEY ("Cod_linea") REFERENCES dwh_torrecontrol."Tdc_cat_lineas_distribucion"("Cod_linea") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

